version: '3.9'

services:
  debian-web:
    build: Ubuntu22-04/
    container_name: ubuntu
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./webpages:/var/www/html"
    restart: unless-stopped

  rhel-web:
    build: Centos/
    container_name: centos
    ports:
      - '8080:80'
      - '4434:443'
    volumes:
      - "./webpages:/usr/share/nginx/html"
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: webnet
